name: flutter_sidekick
description: Widgets for creating Hero-like animations between two widgets within the same screen
version: 0.1.3
homepage: https://github.com/letsar/flutter_sidekick

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
